# Generated by Django 3.2.6 on 2021-08-25 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='firstapp/images')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.website')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
